FROM golang:1.12

RUN go get github.com/sirupsen/logrus
RUN go get github.com/dgraph-io/badger
RUN go get github.com/julienschmidt/httprouter
RUN go get go.etcd.io/etcd/clientv3
RUN go get go.etcd.io/etcd/clientv3/concurrency
RUN go get github.com/Shopify/sarama
RUN go get github.com/gomodule/redigo/redis
RUN go get github.com/huandu/skiplist
RUN go get github.com/BurntSushi/toml
